CaseLabJS/CaseLab2024-team3

src/types/index.ts
=> feat: :sparkles: add types

package-lock.json, package.json, src/api/ApiAttributeController.ts, src/api/ApiAttributeValueController.ts, src/api/ApiAuthController.ts, src/api/ApiDocumentContoller.ts, src/api/ApiDocumentTypeController.ts, src/api/ApiUserController.ts, src/api/index.ts, src/types/index.ts
Добавил контроллер API, а также несколько типов для типизации пагинации.
=> feat: :sparkles: Added API Controller

src/api/ApiAuthController.ts, src/stores/Documents/documents.store.ts, src/stores/Documents/types.ts, src/stores/index.ts
Отрефакторил стор для документов по образцу Владимира, также поправил ошибки с типами и несоответствия.
=> refactor: :recycle: refactor mobx documents store

.dockerignore, Dockerfile, src/api/ApiAuthController.ts, src/components/App/App.tsx, src/components/AppSidebar/AppSidebar.tsx, src/components/Footer/Footer.tsx, src/components/Header/Header.tsx, src/components/HeaderDashboard/HeaderDashboard.tsx, src/components/UI/Sidebar/Sidebar.tsx, src/pages/AdminPage/AdminPage.tsx, src/pages/DocumentsPage.tsx, src/pages/UserDashboardPage/UserDashboardPage.tsx, src/pages/UsersPage.tsx
Приложение обернуто в Docker, пофикшены основные страницы и sidebar в админке под любое разрешение
=> feat: :sparkles: Docker and screen resolution

src/api/ApiDocumentTypeController.ts, src/stores/DocumentTypes/documentTypes.store.ts, src/stores/DocumentTypes/index.ts, src/stores/DocumentTypes/types.ts, src/stores/index.ts
Добавил store для типов документов.
Можем хранить весь список типов документов а также тот, который был последним получен по id через fetchDocumentTypeById
=> feat: :sparkles: added document type store

src/components/Header/Header.tsx, src/components/ProtectedRoute/ProtectedRoute.tsx, src/stores/Auth/auth.store.ts, src/stores/User/index.ts, src/stores/User/user.store.ts
Изменена неработающая кнопка выхода в мобильной версии + к последнему обновлению исправлен prettier
=> fix: :art: Fixed logout button mobile + prettier

eslint.config.js, package-lock.json, package.json
1. Пофиксил eslint.config.
2. Установил пакет "eslint-plugin-prettier".
=> refactor: :wrench: fix eslint.config

src/components/Header/Header.tsx, src/components/Header/User.tsx, src/lib/convertFIO/convertFIO.ts, src/lib/convertFIO/index.ts, src/lib/index.ts, src/stores/Auth/auth.store.ts, src/stores/Users/index.ts
1. Добавил отображение ФИО пользователя в "Header"
2. Добавил функцию "convertFIO" (преобразует ФИО в Фамилия инициалы).
=> feat: :sparkles: add UserFIO | add convertFIO

src/components/UI/Sidebar/Sidebar.tsx
Исправил вертикальный скролл из-за сайдбара, теперь под футером нет лишнего пространства.
=> fix: :bug: fixed vertical scroll in sideabar

src/components/App/App.tsx, src/constants/errorMessage.tsx, src/constants/toast.ts, src/stores/Auth/auth.store.ts, src/stores/Auth/types.ts, src/stores/DocumentTypes/documentTypes.store.ts, src/stores/Documents/documents.store.ts, src/stores/Users/types.ts, src/stores/Users/users.store.ts
-Добавлен вывод ошибок в консоль и toast
-Исправлен баг toast(Отображение происходило только при смене компонентов)
-Код сторов приведён к единому стилю
-Добавлен toast при успешном удалении,создании,редактировании элемента
=> refactor: :recycle: Добавляет обработку ошибок в Mobx сторах

src/components/App/providers/router/AppRouter.tsx, src/pages/SignInPage/SignInPage.tsx
Пофикшен перевод на страницу админа при входе админа
=> fix: :bug: Fixed admin redirection

src/constants/toast.ts, src/stores/Attributes/attributes.store.ts, src/stores/Attributes/index.ts, src/stores/Attributes/types.ts, src/stores/index.ts
=> feat: :sparkles: add MobX attributes store

src/api/ApiUserController.ts, src/components/AdminDialog/AdminDialog.tsx, src/components/DataTable/DataTable.tsx, src/components/Toaster/Toaster.tsx, src/constants/admin.ts, src/pages/UsersAdminPage/UsersAdminPage.tsx, src/stores/Users/types.ts, src/stores/Users/users.store.ts, src/types/adminTypes.ts, src/types/index.ts
*Увеличивает задержку всплывающего окна
*Фикс стора юзеров
=> Feature/user-list Добавляет страницу списка юзеров

src/components/CreateDocument/CreateDocument.tsx, src/components/CreateDocument/createDocuments.types.ts, src/constants/createDocument.ts, src/pages/UserDocumentsPage/UserDocumentsPage.tsx, src/types/index.ts
Добавлен компонент создания документа со стороны пользователя
=> feat: :sparkles: Added document creation component

src/components/CreateDocument/CreateDocument.tsx, src/components/CreateDocument/createDocuments.types.ts, src/pages/UserDocumentsPage/UserDocumentsPage.tsx
Пофикшен баг с обновлением таблицы(id и именем пользователя) после создания документа
=> fix: :bug: Fixed bug with update table

src/components/CreateDocument/CreateDocument.tsx
Исправлен баг с кодированием Base64 при создании документа
=> fix: :bug: Fixed base64 coding

src/api/ApiDocumentController.ts, src/constants/toast.ts, src/pages/UserDashboardIndexPage/UserDashboardIndexPage.tsx, src/stores/Documents/documents.store.ts, src/stores/Documents/types.ts, src/types/index.ts
в рамках таски также
- актуализировал типы для **Document** согласно текущего состояния в **swagger** (и с учетом анонсированного на сегодня бэком обновления  **v1/document** на **POST** с **author/documentId -> id**)
- добавил в индексную страницу userDashboard кол-во отправленных на подпись
если что упустил - пишите
=> MobX на подписи

src/components/Header/Header.tsx, src/components/UpdatePasswordDialog/UpdatePasswordDialog.tsx, src/pages/SignInPage/SignInPage.tsx, src/stores/Auth/auth.store.ts
*Удаляет неиспользуемый пустой файл
*Фиксит ошибку No refresh token до авторизации
*Фиксит ошибку в консоли "Нахождение кнопки в кнопке"
=> fix: Исправляет ошибку кнопка в кнопке

src/api/ApiAttributeController.ts, src/api/ApiDocumentController.ts, src/api/ApiUserController.ts, src/components/Header/Header.tsx, src/constants/authConstants.ts, src/constants/toast.ts, src/stores/Auth/auth.store.ts, src/stores/Voting/index.ts, src/stores/Voting/types.ts, src/stores/Voting/voting.store.ts, src/types/index.ts
*Добавляет методы в контроллер и mobx на голосование 
*Изменяет название вкладок в header
*Добавляет автообновление токена
*Изменияет в контроллерах атрибутов и юзеров put на patch
=> feat: :sparkles: Добавляет Mobx на голосование

src/api/ApiDocumentController.ts, src/components/Action/ActionSendForSign.tsx, src/components/Action/ActionSign.tsx, src/components/Action/ActionSignByAuthor.tsx, src/components/Action/index.ts, src/components/App/providers/router/AppRouter.tsx, src/components/UserSelectDialog/UserSelectDialog.tsx, src/constants/defaultConstants.ts, src/constants/routes.ts, src/constants/sentForUserDocument.ts, src/pages/DocumentPage/DocumentPage.tsx, src/pages/UserAwaitingSignPage/UserAwaitingSignPage.tsx, src/pages/UserDocumentsPage/UserDocumentsPage.tsx, src/pages/UserSentForSignPage/UserSentForSignPage.tsx, src/stores/Documents/documents.store.ts
Добавил UI на подписание документов.
Сейчас в документах, ожидающих подписание есть лишние документы приходящие с бекенда.
Подписать документ можно из меню в таблице или на странице самого документа.
=> feat: :sparkles: Added documents sign

src/components/ProtectedRoute/ProtectedRoute.tsx, src/pages/UserDocumentsPage/UserDocumentsPage.tsx
Исправлены баги с перенаправлением на страницу авторизации при ненахождении токена и с ошибками в консоли при загрузке документов пользователя
=> fix: :bug: Fixed errors with token and document loading

src/components/Action/ActionSendForSign.tsx, src/components/App/providers/router/AppRouter.tsx, src/constants/routes.ts, src/pages/AdminIndexPage/AdminIndexPage.async.tsx, src/pages/AdminIndexPage/AdminIndexPage.tsx, src/pages/AdminIndexPage/index.tsx
Добавил основную страницу админки, по аналогии с основной страницей пользователя.
=> feat: :sparkles: Add admin Index page

src/api/ApiAttributeController.ts, src/api/ApiDocumentController.ts, src/api/ApiUserController.ts, src/components/Action/ActionSendForSign.tsx, src/components/Header/Header.tsx, src/components/UserSelectDialog/UserSelectDialog.tsx, src/constants/authConstants.ts, src/constants/toast.ts, src/index.css, src/pages/DocumentPage/DocumentPage.tsx, src/pages/UserDashboardIndexPage/UserDashboardIndexPage.tsx, src/pages/UserDocumentsPage/UserDocumentsPage.tsx, src/stores/Auth/auth.store.ts, src/stores/Documents/documents.store.ts, src/stores/Voting/index.ts, src/stores/Voting/types.ts, src/stores/Voting/voting.store.ts, src/types/index.ts
Теперь пользователь не может отправить документ на подпись сам себе.
Поправил темную тему для react-select, теперь в темной тебе при выборе пункта и при вводе в input текст белый (был черный, его не было видно)
Исправил количество документов на главной странице пользователя, разделил пагинацию на две: для обычных документов и документов, ожидающих подписание.
=> fix: 🐛 Remove current user from send for sign

src/api/ApiDocumentController.ts, src/components/App/providers/router/AppRouter.tsx, src/constants/routes.ts, src/constants/sideBar.ts, src/pages/DocumentPage/DocumentPage.tsx, src/pages/UserAwaitingSignPage/UserAwaitingSignPage.tsx, src/pages/UserDashboardIndexPage/UserDashboardIndexPage.tsx, src/pages/UserSignedDocuments/UserSignedDocuments.async.tsx, src/pages/UserSignedDocuments/UserSignedDocuments.tsx, src/pages/UserSignedDocuments/index.ts, src/stores/Documents/documents.store.ts
Разделил документы до подписания и после подписания,
Подписанные документы переехали во вкладку "Подписанные документы".
=> feat: :sparkles: Separate docs before and after sign

src/components/DataTable2/ui/TableBody.tsx, src/pages/DocumentPage/DocumentPage.tsx, src/pages/UserDocumentsPage/UserDocumentsPage.tsx, src/pages/UserSentForSignPage/UserSentForSignPage.tsx
Исправил пагинацию документов, для получения строк таблицы теперь используется getCoreRowModel вместо getRowModel, в которой были пустые строки.
=> fix: :bug: fix pagination

index.html, src/components/AppSidebar/AppSidebar.tsx, src/components/Footer/Footer.tsx, src/components/Header/Header.tsx, src/components/UpdatePasswordDialog/UpdatePasswordDialog.tsx, src/pages/UserDashboardIndexPage/UserDashboardIndexPage.tsx
Добавил подсветку текущего раздела (если у пользователя обе роли - user и admin), добавил title и favicon
Пофиксил что при клике на логотип и у пользователя только роль admin его перенаправляет на страницу /admin, до этого перенаправляло на /app, что приводило к 404 странице
=> feat: Add highlight header section, favicon and title

src/components/DataTable2/DataTable2.tsx, src/components/DataTable2/ui/TableBody.tsx
Исправил сортировку, до этого с getCoreRowModel она не работала.
Сейчас при сортировке на второй странице нас перекидывает на первую страницу, если у кого-то есть идеи как исправить было бы очень хорошо.
=> fix: :bug: fix sorting

src/components/CreateDocument/CreateDocument.tsx, src/components/CreateDocument/createDocuments.types.ts, src/constants/createDocument.ts, src/types/index.ts
Исправлено создание документа с учетом правок сервера
=> fix: :bug: Fixed create document

src/components/Action/ActionSendForSign.tsx, src/components/CreateDocument/CreateDocument.tsx, src/components/DataTable2/ui/TableHeader.tsx, src/components/Footer/Footer.stories.tsx, src/components/Header/Header.stories.tsx, src/components/HeaderDashboard/HeaderDashboard.stories.tsx, src/components/Layout/Layout.stories.tsx, src/components/UI/AlertDialog/AlertDialog.stories.tsx, src/components/UI/Form/Form.stories.tsx, src/components/UserSelectDialog/UserSelectDialog.tsx, src/constants/createDocument.ts, src/index.css, src/pages/UserAwaitingSignPage/UserAwaitingSignPage.tsx, src/pages/UserSignedDocuments/UserSignedDocuments.tsx, src/types/index.ts
Исправлена доступность кнопки при незаполненности обязательных полей и загрузки файла + подправлен Prettier
=> fix: :bug: Fixed availability of the button when filling in fields

src/components/Action/ActionDelete.tsx, src/components/UpdateDocument/UpdateDocument.tsx, src/pages/DocumentPage/DocumentPage.tsx
1. Изменил форму редактирования документа в соответствии с последними изменениями в бэке (в части замены файла).
2. Добавил модалку на подтверждение удаления документа на странице документа.
3. Убрал кнопку удаления документа для документов, имеющих статус, с которым их удалить не получится.
=> fix: :alien: fix document page | fix update document form

Dockerfile, nginx.conf, src/components/App/providers/router/AppRouter.tsx, src/components/ProtectedRoute/ProtectedRoute.tsx, src/constants/routes.ts
Добавлен конфиг нджинкс и отредактирован докер
=> feat: :rocket: Server deploy

package-lock.json, package.json, src/components/Action/ActionEdit.tsx, src/components/Action/ActionEditAttributes.tsx, src/components/Action/ActionEditDocTypes.tsx, src/components/CreateDocument/CreateDocument.tsx, src/components/CreateUser/CreateUserForm.tsx, src/components/CreateUser/createUsersForm.types.ts, src/components/UI/Form/Form.tsx, src/components/UI/Form/FormFieldInput.tsx, src/components/UpdateDocument/UpdateDocument.tsx, src/components/UpdatePasswordDialog/UpdatePasswordDialog.tsx, src/components/UserSelectDialog/UserSelectDialog.tsx, src/constants/adminAttributes.ts, src/constants/adminDocumentType.ts, src/constants/authConstants.ts, src/constants/createDocument.ts, src/constants/updateDocument.ts, src/constants/updateUser.ts, src/constants/userDocument.ts, src/constants/usersListTable.ts, src/pages/SignInPage/SignInPage.tsx, src/pages/UsersAdminPage/UsersAdminPage.tsx
*Приводит формы в один дизайн
*Добавляет zod для создания пользователя и формы авторизации
*Добавляет валидацию для смены пароля
-Хотела еще добавить zod для создания документа,но как-то мало времени переписывать 
*Добавляет пометку в описание,что Поля с * обязательны
*Добавляет * в те лейблы,где было пропущено 
Если кто-то  будет мёржить,то выберите,пожалуйста,merge and squash,чтобы один коммит был
=> refactor: Приводит формы в один вид

src/pages/DocumentPage/DocumentPage.tsx, src/pages/UserAwaitingSignPage/UserAwaitingSignPage.tsx, src/pages/UserDocumentsPage/UserDocumentsPage.tsx
1. Удалил в таблице кнопку "отправить на доработку" если документ - на голосовании
2. При подписывании документа со страницы документа отображается корректные документы в таблице (до этого только после обновления)
3. При подписывании документов изменяются значения в сайдбаре.
=> fix: 🐛  deleted buttons for signed if document for voting

src/components/Action/ActionDelete.tsx, src/constants/defaultConstants.ts, src/constants/updateDocument.ts, src/constants/userDocument.ts, src/pages/DocumentPage/DocumentPage.tsx, src/pages/UserDocumentsPage/UserDocumentsPage.tsx
1. Отрегулировал наличие/отсутствие кнопок удаления и изменения документа на странице документа. Теперь они доступны при переходе из любого пункта бокового меню, если вы являетесь автором документа:
- кнопка удаления доступна для документов со статусами Черновик / Одобрен / Отклонен / Требуется доработка;
- кнопка изменения доступна для документов со статусами Черновик / Требуется доработка / Ожидает подписи контрагентом.
2. Задал min-width документа на странице.
=> fix: :bug: provide appropriate action buttons on document page

src/pages/UserAwaitingSignPage/UserAwaitingSignPage.tsx
Исправил количество документов у "Подписанные документы" если подписали у страницы "Ожидают подписания"
=> fix: :bug: fixed docs after signed count

package-lock.json, src/api/ApiDocumentController.ts, src/pages/DocumentPage/DocumentPage.tsx, src/pages/DocumentPage/ui/DocumentBadge.tsx, src/pages/DocumentPage/ui/DocumentDate.tsx, src/stores/Documents/documents.store.ts, src/types/index.ts
1. Добавил дату изменения документа на странице документа (если он менялся). При сохранении изменений она меняется на дату последней версии документа.
2. Поправил вёрстку страницы документа.
Баг: если изменить документ, у которого до этого не было версий, то после сохранения изменений и закрытия модального окна не появляется дата изменения документа. Она появляется только после перезагрузки страницы или повторного захода на неё.
P.S. У меня при выполнении скрипта husky были ошибки, коммитил с флагом --no-verify.
=> fix: document creation date | adjust document page

package-lock.json, package.json, src/api/ApiDocumentController.ts, src/components/UI/Accordion/Accordion.stories.tsx, src/components/UI/Accordion/Accordion.tsx, src/components/UI/Accordion/index.ts, src/components/UI/index.ts, src/components/UpdateDocument/UpdateDocument.tsx, src/pages/DocumentPage/DocumentPage.tsx, src/pages/DocumentPage/ui/DocumentBadge.tsx, src/pages/DocumentPage/ui/DocumentDate.tsx, src/pages/UserDashboardIndexPage/UserDashboardIndexPage.tsx, src/stores/Documents/documents.store.ts, src/types/index.ts, tailwind.config.js
Добавил UI-компонент Accordion (не забудьте npm i).
Добавил версии документа.
Сохраняется баг: при изменении документа список версий обновится только после перезагрузки страницы.
=> feat: :sparkles: add document versions
